config:
    slot:
        price: 100.0
        maximum: 20
        increase: 50.0
#Skybank version 1.5.3 configuration
#Please refer to http://dev.bukkit.org/server-mods/skybank/pages/configuration/
#for more information on the configuration.